### PR TITLE
Switch to OSQP_jll binaries for Julia versions >= 1.3

### PR DESCRIPTION
**Pull request by kerrysnyder**
New contributor, definitely open to feedback and discussion.

This pull request would switch OSQP.jl from using the upstream releases and a build.jl file to the new BinaryBuilder/Yggdrasil/Artifacts system released in [Julia 1.3](https://julialang.org/blog/2019/11/artifacts/).

To get here, the following steps have been taken:
1. A new 'build_tarballs.jl' was created for OSQP using the [BinaryBuilder wizard](https://github.com/JuliaPackaging/BinaryBuilder.jl) 
2. This was merged into Yggdrasil: JuliaPackaging/Yggdrasil#842
3. OSQP_jll was automatically generated [here](https://github.com/JuliaBinaryWrappers/OSQP_jll.jl) along with the compiled [releases](https://github.com/JuliaBinaryWrappers/OSQP_jll.jl/releases) for all supported platforms
4. This change, which adds the OSQP_jll dependency and uses it for Julia versions >= 1.3

At the moment, tests in "polishing" and "update_matrices" are failing, but this seems to [already happen](https://travis-ci.org/github/oxfordcontrol/OSQP.jl/builds/651695610) on 1.3 and nightly.

IMO the biggest benefit is trivial support for all of Julia's target platforms, rather than the [four](https://github.com/oxfordcontrol/OSQP.jl/blob/master/deps/build.jl#L39) currently available from upstream. With this change, I have successfully tested OSQP.jl on AArch64, specifically the NVIDIA Tegra X2. However, I can understand if the preferred approach would be to not introduce another build system and instead add more upstream releases and continue to pull from there instead.

### CODE REVIEW

**Comment by blegat** [comment]
IIUC, reading the Yggdrasil README, it is possible to generate a binary provider script to replace `deps/build.jl` to dowload the binary from Yggdrasil instead. This would provide a more consistent experience if the same binaries are used accross all versions of Julia even if Julia 1.2 uses BinaryProvider and Julia 1.3 uses OSQP_jll.

**Comment by giordano** [comment]
There is a new pull request to add support for MKL: https://github.com/JuliaPackaging/Yggdrasil/pull/846.  Is this something desirable?

**Comment by kerrysnyder** [comment]
Add Yggdrasil-generated build.jl to grab JuliaBinaryWrappers/OSQP_jll binaries for pre-1.3 Julia versions.

Re: MKL, I'm not the decision maker, but it looks like that's what the current binaries use, and matching that is important, so I would vote yes.

**Comment by jd-lara** [comment]
> Add Yggdrasil-generated build.jl to grab JuliaBinaryWrappers/OSQP_jll binaries for pre-1.3 Julia versions.
> 
> Re: MKL, I'm not the decision maker, but it looks like that's what the current binaries use, and matching that is important, so I would vote yes.

Yeah, the current binaries use MKL but they get it from the conda sources 

https://github.com/oxfordcontrol/osqp/blob/66e8dcee624c9cdc91ec3c2a60653653d9248111/ci/travis/script.sh#L7

I just added a link to the MKL_jll from the julia binaries.

**Comment by ViralBShah** [comment]
It would be nice to get this merged.

**Comment by bstellato** [comment]
Sorry about the delay! That's a great PR. I am drafting release 0.6.2 right now. It incorporates a few useful fixes. Would it be possible to adjust these edits for version 0.6.2?

**Comment by ViralBShah** [comment]
I think this PR is fairly independent. The main issue is that it is failing.

**Comment by ViralBShah** [comment]
The failing test is:

https://travis-ci.org/github/oxfordcontrol/OSQP.jl/jobs/674406018#L296
```
 Test: non_convex.jl
ERROR in LDL_factor: Error in KKT matrix LDL factorization when computing the nonzero elements. The problem seems to be non-convex
ERROR in osqp_setup: KKT matrix factorization.
```

Would you know why this might be happening? Is it possibly because OSQP is not compiled right?

**Comment by ViralBShah** [comment]
@bstellato I misunderstood. Do you mean version 0.6.2 of osqp upstream? Yes, I'll do that right away.

**Comment by ViralBShah** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/2361

**Comment by ViralBShah** [comment]
I see that the build is trying to use Pardiso: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=8286&view=logs&jobId=a317c404-c21f-59c2-b31d-c5d516a17107&j=a317c404-c21f-59c2-b31d-c5d516a17107&t=47c6b8f6-86aa-52e1-8dca-5b6054b6daa0

Does the OSQP.jl package use code paths that need Pardiso? In that case, we can add MKL_jll as a dependency. However, it is not clear if that is why the tests are failing.

**Comment by ViralBShah** [comment]
Note that to pull in 0.6.2, https://github.com/JuliaRegistries/General/pull/27403 needs to merge which may happen soon.

**Comment by bstellato** [comment]
Thanks for being so quick! OSQP can use pardiso by dynamically loading mkl library. However, that's not required and I would not add it as a dependency. 

The failing test seems the "polish_random" one that loads some stored random data as `.jld2`. The error might be simply happening because something related to the random number generator has changed. I would either ignore/remove that test or compare with the solution computed at test time with another `JuMP` solver.

**Comment by kerrysnyder** [comment]
After a rebase onto upstream-master, it looks like the CI failures are not necessarily new as compared to the [latest master push](https://github.com/oxfordcontrol/OSQP.jl/actions/runs/448971152) (although the errors are slightly different now)

The bump to 0.6.2 should be straightforward once it makes it into the registry, but Yggdrasil's generate_buildjl.jl is not working for me right now.

**Comment by ViralBShah** [comment]
I merged the new release. Can you close and reopen this PR so that it ends up pulling 0.6.2 and runs the testsuite with the new binaries?

Interestingly, on master, the failures are on all the 32-bit builds, but here it is only 32-builds for 1.0.

**Comment by ViralBShah** [comment]
Yup it's using the new binaries - which are giving the same results as earlier. So I guess this is good to go?

**Comment by bstellato** [comment]
Sounds great! Thanks a lot.

**Pull request merged**
