### PR TITLE
Update to MOI v0.9.5

### PR DESCRIPTION
**Pull request by blegat**
Closes https://github.com/oxfordcontrol/OSQP.jl/issues/64

### CODE REVIEW

**Comment by blegat** [comment]
@bstellato Any idea why
https://github.com/oxfordcontrol/OSQP.jl/blob/d36d3e0fc8b07f0a5771d14763930eeb3acc7822/src/interface.jl#L445-L446
is failing on 32 bits ?

**Comment by tkoolen** [comment]
With what options are the binaries compiled? I see

https://github.com/oxfordcontrol/osqp/blob/d7eeb245d5b7f0195bfc35b6cb71f4570d7ca18b/include/osqp.h#L419-L420

and

https://github.com/oxfordcontrol/osqp/blob/d7eeb245d5b7f0195bfc35b6cb71f4570d7ca18b/include/glob_opts.h#L73-L78

and

https://github.com/oxfordcontrol/osqp/blob/657a3b117320c4f8ecb57e27011e75e63f61ce4d/include/glob_opts.h#L81-L85

which means that there are a couple of options for what `c_int` and `c_float` are.

**Comment by bstellato** [comment]
We compile the solver with default options for the binaries (see [here](https://github.com/oxfordcontrol/osqp/blob/657a3b117320c4f8ecb57e27011e75e63f61ce4d/ci/appveyor/deploy.cmd#L16-L25) for windows). Default options are: `DLONG=ON` and `DFLOAT=OFF`. 

As @tkoolen mentioned, we define `c_int` and `c_float` [here](https://github.com/oxfordcontrol/osqp/blob/657a3b117320c4f8ecb57e27011e75e63f61ce4d/include/glob_opts.h#L74-L85) according to the option.

In OSQP.jl we map the short/long int C type to the julia one in [here](https://github.com/oxfordcontrol/OSQP.jl/blob/d36d3e0fc8b07f0a5771d14763930eeb3acc7822/src/types.jl#L4-L10). This made it work for 32bit until now. Did anything in Julia change to make it fail? Our binary build system did not change since last OSQP.jl release.

**Comment by blegat** [comment]
I am merging to allow to check that OSQP master work with MOI master (see https://travis-ci.com/blegat/SolverTests/jobs/249637424) before releasing MOI v0.9.6. I am opening a separate issue about the 32-bit issue.

**Pull request merged**
