### PR TITLE
Release 0.5.2

### LINKED ISSUE #50: passing verbose option
It seems that the option passing from JuMP might be broken. The instructions here https://osqp.org/docs/parsers/jump.html?highlight=verbose are outdated but I have been trying to use the same configuration used by other solvers. 

```Julia
using JuMP
using OSQP
OSQP_optimizer = JuMP.with_optimizer(OSQP.Optimizer, verbose = false)
m = Model(OSQP_optimizer)
```

And this other alternative

```Julia
OSQP_optimizer = JuMP.with_optimizer(OSQP.Optimizer, settings = Dict(:verbose => false))
m = Model(OSQP_optimizer)
```

It returns an unsupported keyword error in both cases. 

```
MethodError: no method matching OSQP.MathOptInterfaceOSQP.Optimizer(; settings=Dict(:verbose=>false))
Closest candidates are:
  OSQP.MathOptInterfaceOSQP.Optimizer() at /Users/jdlara/.julia/packages/OSQP/H4U2v/src/MOI_wrapper.jl:76 got unsupported keyword argument "settings"
```

### PR DESCRIPTION
**Pull request by bstellato**
Create new release.

Fix #50.

### CODE REVIEW

**Comment by bstellato** [comment]
@JuliaRegistrator register()

**Comment by blegat** [comment]
I didn't know you could make a release on an open PR. I though it should be merge on the master branch first

**Comment by tkoolen** [comment]
> I didn't know you could make a release on an open PR. I though it should be merge on the master branch first

Yeah, that's what I've been doing.

**Comment by bstellato** [comment]
You just need to comment below a commit (not the PR). I will merge once the https://github.com/JuliaRegistries/General/pull/967 is accepted.

**Pull request merged**
