### PR TITLE
Replace flaky warm start time test with one based on iteration count.

### PR DESCRIPTION
**Pull request by tkoolen**

### CODE REVIEW

**Comment by bstellato** [comment]
Is there an issue with the warm start times? There is also an issue here https://github.com/oxfordcontrol/osqp/issues/115

We might have to fix the internal timings. @gbanjac

**Comment by tkoolen** [comment]
I'm not sure, but in general I'm kind of allergic to tests based on timing, especially if it can be avoided easily. A context switch could easily cause this test to fail.

**Comment by bstellato** [comment]
OK understood, thanks!

**Comment by gbanjac** [comment]
@bstellato I think this is related to [this comment](https://github.com/oxfordcontrol/OSQP.jl/pull/41#issuecomment-459680457) by @migarstka

**Pull request merged**
